# 01-Intro Homework

In [1]:
import pandas as pd
import numpy as np

## Q1. What's the version of Pandas that you installed?

In [2]:
pd.__version__

'2.3.1'

## Getting the data

In [3]:
df = pd.read_csv('car_fuel_efficiency.csv')
df.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

## Q2. How many records are in the dataset?

In [4]:
df.count()

engine_displacement    9704
num_cylinders          9222
horsepower             8996
vehicle_weight         9704
acceleration           8774
model_year             9704
origin                 9704
fuel_type              9704
drivetrain             9704
num_doors              9202
fuel_efficiency_mpg    9704
dtype: int64

## Q3. How many fuel types are presented in the dataset?

In [5]:
df['fuel_type'].unique()

array(['Gasoline', 'Diesel'], dtype=object)

## Q4. How many columns in the dataset have missing values?

In [6]:
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

## Q5. What's the maximum fuel efficiency of cars from Asia?

In [7]:
df.groupby('origin').fuel_efficiency_mpg.max()

origin
Asia      23.759123
Europe    25.967222
USA       24.971452
Name: fuel_efficiency_mpg, dtype: float64

## Q6. Median Value of Horsepower

In [8]:
# Find the median value of horsepower column in the dataset.
df['horsepower'].median()

np.float64(149.0)

In [9]:
# Next, calculate the most frequent value of the same horsepower column.
df['horsepower'].mode()

0    152.0
Name: horsepower, dtype: float64

In [10]:
# Use fillna method to fill the missing values in horsepower column with the most frequent value from the previous step.
df['horsepower'] = df['horsepower'].fillna(152)

In [11]:
# Now, calculate the median value of horsepower once again.
df['horsepower'].median()

np.float64(152.0)

## Q7. Sum of weights

Select all the cars from Asia

In [12]:
df_asia = df[
    df['origin']=="Asia"
]

Select only columns vehicle_weight and model_year

In [13]:
df_asia = df_asia[['vehicle_weight', 'model_year']]

Select the first 7 values

In [14]:
df_asia = df_asia.iloc[0:7]

Get the underlying NumPy array. Let's call it X

In [15]:
X = df_asia[['vehicle_weight', 'model_year']].values
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

### Compute matrix-matrix multiplication between the transpose of X and X. 

In [16]:
XTX = X.T.dot(X)
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

### Invert XTX

In [17]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

### Create an array y

In [18]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

### Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.

In [19]:
w = XTX_inv.dot(X.T).dot(y)
w

array([0.01386421, 0.5049067 ])

### What's the sum of all the elements of the result?

In [20]:
weights = w.sum()
weights

np.float64(0.5187709081074016)